Adding hook for custom post status with tests
Automattic/msm-sitemap pull request #176
Opened 2023-11-28 18:11 UTC by elysium001

**Pull Request: Add `msm_sitemap_post_status` WordPress Hook**

**Description:** This pull request introduces a new WordPress hook, `msm_sitemap_post_status`, to facilitate customization of post statuses for inclusion in the sitemap. This feature was specifically requested by a customer to enhance the flexibility of handling custom post statuses in the sitemap functionality.

**Changes Introduced:**

- Added `msm_sitemap_post_status` hook in `msm-sitemap.php`.
- Documented usage of the new hook in the codebase and readme
- Added unit tests to make sure other query and helper functions still work accordingly.

**Background:** A customer expressed the need for a way to use a post status other than 'published' to build the sitemap, prompting the development of this feature. The introduction of the `msm_sitemap_post_status` hook allows developers to extend the sitemap functionality easily and integrate their custom post statuses.

**Related Issues:** 
- internal customer discussion and [P2](https://salesforcep2.wordpress.com/2023/11/21/notes-msm-sitemaps-troubleshooting/)

**Reviewers:** TBD

2023-11-29 19:05 UTC, GaryJones requested changes

2023-11-29 19:05 UTC, GaryJones commented on tests/test-sitemap-functions.php
> +	 * @param int $expected_count Number of posts expected to be returned.
```suggestion
	 * @param string  $sitemap_date   Date in Y-M-D format.
	 * @param string  $limit          Max number of posts to return.
	 * @param int     $expected_count Number of posts expected to be returned.
```

2023-11-29 19:05 UTC, GaryJones commented on tests/test-sitemap-functions.php
> +	 function test_get_post_status() {
```suggestion
	function test_get_post_status() {
```

2023-11-29 19:05 UTC, GaryJones commented on tests/test-sitemap-functions.php
> +	 }
```suggestion
	}
```

2023-11-29 19:05 UTC, GaryJones commented on msm-sitemap.php
> +	public static function get_post_status() {
Does this method need to be `public`?

2023-11-29 22:01 UTC, elysium001 commented on msm-sitemap.php
> +		return apply_filters('msm_sitemap_post_status', 'publish');
added checks against get_post_stati values and hook properly documented.

2023-11-29 22:05 UTC, elysium001 commented on msm-sitemap.php
> +	public static function get_post_status() {
while it's not required, it does make it much easier to test such as the get_post_stati values mechanism.

2023-11-29 22:34 UTC, elysium001 commented on tests/test-sitemap-functions.php
> +		add_filter( 'msm_sitemap_post_status', array( $this, 'add_post_status_to_msm_sitemap' ) );
I hear that. I took a stab at this but kept running into a strange issue with anonymous functions not respecting `remove_filter` in the tests. I ended up refactoring slightly to DRY these calls though.

2023-12-01 14:59 UTC, GaryJones approved these changes

2023-12-01 17:37 UTC, merged